title: Calvin | Software Engineer
description: Transitioning to DevOps âž” DevSecOps | Python & Automation Specialist
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

baseurl: ""
url: "https://clsw-tech-base.github.io/"

github_username: "Calvin Lim Seng Wah"
linkedin_username: "Seng Wah Calvin Lim"

header_pages:
  - index.md
  - resume.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
  - .gitignore
  - README.md

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
